# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [40]:
import pandas as pd
import numpy as mp
from scipy.spatial.distance import pdist, squareform

In [41]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [42]:
display(data.head())
data.shape

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

(68584, 7)

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [43]:
data2 = data.groupby(["CustomerID", "ProductName"])["Quantity"].sum().reset_index()
display(data2.head())

   CustomerID                    ProductName  Quantity
0          33               Apricots - Dried         1
1          33              Assorted Desserts         1
2          33        Bandage - Flexible Neon         1
3          33  Bar Mix - Pina Colada, 355 Ml         1
4          33         Beans - Kidney, Canned         1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [46]:
data_pivot = pd.pivot_table(data, values = "Quantity", index=["ProductName"], columns = ["CustomerID"], aggfunc=sum)
data_pivot.fillna(0, inplace=True)
display(data_pivot.head())

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [47]:
# https://en.wikipedia.org/wiki/Euclidean_distance
similarity_m = pd.DataFrame(1/(1 + squareform(pdist(data_pivot.T, 'euclidean'))), 
                         index=data_pivot.columns, columns=data_pivot.columns)
display(similarity_m.head())

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.077421,0.087047,0.081800,0.080634,0.082709,0.074573,0.083020,0.081503,0.080070,...,0.004811,0.004669,0.004412,0.005019,0.004312,0.004515,0.004583,0.004355,0.004167,0.004333
200,0.077421,1.000000,0.078448,0.076435,0.073693,0.075255,0.075956,0.076435,0.077674,0.076923,...,0.004824,0.004681,0.004431,0.005047,0.004311,0.004521,0.004614,0.004367,0.004166,0.004335
264,0.087047,0.078448,1.000000,0.080070,0.081800,0.080350,0.076923,0.080634,0.082100,0.078448,...,0.004822,0.004674,0.004416,0.005035,0.004322,0.004543,0.004595,0.004365,0.004179,0.004333
356,0.081800,0.076435,0.080070,1.000000,0.076435,0.078187,0.075025,0.082403,0.077171,0.075956,...,0.004816,0.004671,0.004416,0.005038,0.004310,0.004526,0.004578,0.004365,0.004175,0.004339
412,0.080634,0.073693,0.081800,0.076435,1.000000,0.078711,0.075025,0.082403,0.078187,0.078448,...,0.004810,0.004702,0.004414,0.005034,0.004318,0.004530,0.004578,0.004367,0.004177,0.004349

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [59]:
similarities = similarity_m[200].sort_values(ascending=False)[1:6]
display(similarities.head(5))
similar_ids=list(similarities.index)

print(similar_ids)

CustomerID
3317    0.084959
1072    0.083972
3535    0.082403
1920    0.082100
3909    0.080920
Name: 200, dtype: float64

[3317, 1072, 3535, 1920, 3909]

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [72]:
records=data2.loc[data2['CustomerID'].isin(similar_ids)]
display(records)

      CustomerID                        ProductName  Quantity
1082        1072  Appetizer - Mini Egg Roll, Shrimp         1
1083        1072          Appetizer - Sausage Rolls         1
1084        1072             Beans - Kidney, Canned         1
1085        1072     Beef - Montreal Smoked Brisket         1
1086        1072                Beef - Striploin Aa         1
...          ...                                ...       ...
3263        3909       Wine - Charddonnay Errazuriz         2
3264        3909           Wine - Fume Blanc Fetzer         1
3265        3909     Wine - Magnotta, Merlot Sr Vqa         1
3266        3909                Wine - Toasted Head         1
3267        3909           Wine - Valpolicella Masi         1

[262 rows x 3 columns]

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [92]:
top_products = records.groupby(["ProductName"])["Quantity"].sum().reset_index()
top_products = top_products.sort_values("Quantity",ascending=False)
display(top_products.head(20))

                         ProductName  Quantity
159     Soup - Campbells Bean Medley         4
103  Muffin - Carrot Individual Wrap         3
8                           Bay Leaf         3
136                    Pork - Kidney         3
129            Pepper - Black, Whole         3
88                     Lamb - Ground         3
185                      Wanton Wrap         3
48              Coffee - Irish Cream         2
173           Tart Shells - Sweet, 4         2
172                     Tahini Paste         2
46     Chips Potato Salt Vinegar 43g         2
171          Table Cloth 54x72 White         2
45           Chinese Foods - Chicken         2
94              Lime Cordial - Roses         2
55                Crush - Cream Soda         2
140                  Quiche Assorted         2
164          Soupfoamcont12oz 112con         2
89              Lamb - Pieces, Diced         2
43               Cheese Cloth No 100         2
60                        Dried Figs         2

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [102]:
##records of cid=200
records_bought=data2.loc[data2['CustomerID']==200]
##creating list with unique products bought
products_bought=list(records_bought.ProductName.unique())
print(len(products_bought))
##print(products_bought)

##creating list with unique products bought by similar customers
products_similar=list(top_products.ProductName.unique())
print(len(products_similar))
##print(products_similar)


## creating list bought by similar customers not bought already by customer 200
products_to_recommend=[i for i in products_similar if i not in products_bought]
print(len(products_to_recommend))
print(products_to_recommend)

72
207
165
['Soup - Campbells Bean Medley', 'Muffin - Carrot Individual Wrap', 'Bay Leaf', 'Pork - Kidney', 'Wanton Wrap', 'Chips Potato Salt Vinegar 43g', 'Table Cloth 54x72 White', 'Chinese Foods - Chicken', 'Lime Cordial - Roses', 'Soupfoamcont12oz 112con', 'Lamb - Pieces, Diced', 'Cheese Cloth No 100', 'Dried Figs', 'Eggplant - Asian', 'Soup - Campbells, Beef Barley', 'Ezy Change Mophandle', 'Fish - Scallops, Cold Smoked', 'Foam Dinner Plate', 'Fondant - Icing', 'Garbage Bags - Clear', 'Sole - Dover, Whole, Fresh', 'Sausage - Liver', 'Scallops - 10/20', 'Ice Cream Bar - Hageen Daz To', 'Ice Cream Bar - Oreo Cone', 'Juice - Orange', 'Scallops 60/80 Iqf', 'Scampi Tail', 'Black Currants', 'Wine - Toasted Head', 'Wine - Magnotta, Merlot Sr Vqa', 'Pate - Cognac', 'Wine - Chardonnay South', 'Wine - Charddonnay Errazuriz', 'Beef Wellington', 'Wine - Blue Nun Qualitatswein', 'Wine - Red, Harrow Estates, Cab', 'Beans - Kidney, Canned', 'Bread - Rye', 'Muffin Batt - Blueberry Passion', 'Pasta - Detalini, White, Fresh', 'Cake - Box Window 10x10x2.5', 'Vanilla Beans', 'Cheese - Boursin, Garlic / Herbs', 'Cheese - Brie, Triple Creme', 'Oranges - Navel, 72', 'Pasta - Orecchiette', 'Pasta - Penne, Rigate, Dry', 'Sausage - Breakfast', 'Pasta - Angel Hair', 'Pork - Inside', 'Pastry - Choclate Baked', 'Pepper - Paprika, Hungarian', 'Rice - Jasmine Sented', 'Raspberries - Fresh', 'Phyllo Dough', 'Placemat - Scallop, White', 'Pomello', 'Puree - Passion Fruit', 'Pork - Loin, Bone - In', 'Potatoes - Instant, Mashed', 'Soupcontfoam16oz 116con', 'Sea Bass - Whole', 'Shrimp - Baby, Warm Water', 'Veal - Inside, Choice', 'Veal - Osso Bucco', 'Vol Au Vents', 'Water, Tap', 'Whmis - Spray Bottle Trigger', 'Wine - Cahors Ac 2000, Clos', 'Wine - Ej Gallo Sierra Valley', 'Wine - Fume Blanc Fetzer', 'Wine - Magnotta - Belpaese', 'Wine - Red, Colio Cabernet', 'Wine - Valpolicella Masi', 'Wine - Wyndham Estate Bin 777', 'Wonton Wrappers', 'Yeast Dry - Fermipan', 'Turkey - Whole, Fresh', 'Towels - Paper / Kraft', 'Skirt - 29 Foot', 'Smirnoff Green Apple Twist', 'Sobe - Tropical Energy', 'Soup Campbells - Italian Wedding', 'Pail For Lid 1537', 'Spinach - Baby', 'Sprouts - Baby Pea Tendrils', 'Tofu - Firm', 'Squid - Tubes / Tenticles 10/20', 'Steam Pan - Half Size Deep', 'Sugar - Fine', 'Tea - Decaf Lipton', 'Tea - Herbal Sweet Dreams', 'Tea - Jasmin Green', 'Papayas', 'Anchovy Paste - 56 G Tube', 'Otomegusa Dashi Konbu', 'Cheese - Wine', 'Butter - Unsalted', 'Cheese - Cambozola', 'Cheese - Parmesan Grated', 'Cheese - Victor Et Berthold', 'Chicken - Soup Base', 'Bread - Bistro White', 'Cod - Black Whole Fillet', 'Cookie - Dough Variety', 'Cookies - Assorted', 'Corn Meal', 'Cornflakes', 'Crab - Dungeness, Whole', 'Crab - Imitation Flakes', 'Cup - Translucent 7 Oz Clear', 'Bread Crumbs - Panko', 'Dc Hikiage Hira Huba', 'Appetizer - Sausage Rolls', 'Apricots - Dried', 'Apricots - Halves', 'Bandage - Fexible 1x3', 'Barramundi', 'Beans - Kidney White', 'Beef - Chuck, Boneless', 'Beef - Rib Eye Aaa', 'Berry Brulee', 'Beef - Short Loin', 'Beef - Striploin Aa', 'Beef - Top Sirloin - Aaa', 'Beer - Blue', 'Beer - Rickards Red', 'Beer - Sleemans Cream Ale', 'Curry Paste - Madras', 'Oregano - Dry, Rubbed', 'Macaroons - Two Bite Choc', 'Meldea Green Tea Liquor', 'Milk - 2%', 'Milk Powder', 'Appetizer - Mini Egg Roll, Shrimp', 'Mushroom - Porcini, Dry', 'Nantucket - Pomegranate Pear', 'Nut - Chestnuts, Whole', 'Ocean Spray - Kiwi Strawberry', 'Ocean Spray - Ruby Red', 'Oil - Safflower', 'Oil - Shortening - All - Purpose', 'Onions - Cippolini', 'Longos - Grilled Salmon With Bbq', 'Lettuce - Spring Mix', 'Ecolab - Mikroklene 4/4 L', 'Ice Cream Bar - Drumstick', 'Ecolab - Solid Fusion', 'Fenngreek Seed', 'French Pastry - Mini Chocolate', 'Garlic - Elephant', 'Garlic - Primerba, Paste', 'General Purpose Trigger', 'Gloves - Goldtouch Disposable', 'Guinea Fowl', 'Isomalt', 'Lettuce - Frisee', 'Jagermeister', 'Juice - Apple Cider', 'Kellogs Special K Cereal', 'Ketchup - Tomato', 'Knife Plastic - White', 'Lambcasing', 'Yoghurt Tubes']

In [107]:
top5=top_products.loc[top_products['ProductName'].isin(products_to_recommend)][:5]
print(top5['ProductName'])

159       Soup - Campbells Bean Medley
103    Muffin - Carrot Individual Wrap
8                             Bay Leaf
136                      Pork - Kidney
185                        Wanton Wrap
Name: ProductName, dtype: object

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [115]:
dict_cust_recom = {}
unique_customers = list(data.CustomerID.unique())
print(len(unique_customers))


for x in unique_customers:
    similar_ids=list((similarity_m[x].sort_values(ascending=False)[1:6]).index)
    records=data2.loc[data2['CustomerID'].isin(similar_ids)]
    top_products = (records.groupby(["ProductName"])["Quantity"].sum().reset_index()).sort_values("Quantity",ascending=False)
    records_bought=data2.loc[data2['CustomerID']==x]
    products_bought=list(records_bought.ProductName.unique())
    products_similar=list(top_products.ProductName.unique())
    products_to_recommend=[i for i in products_similar if i not in products_bought]
    top5=top_products.loc[top_products['ProductName'].isin(products_to_recommend)][:5]
    dict_cust_recom[x] = list(top5['ProductName'])

1000

In [116]:
dict_cust_recom[264]

['Soupfoamcont12oz 112con',
 'Wine - Two Oceans Cabernet',
 'Bread - Italian Roll With Herbs',
 'Veal - Inside, Choice',
 'Fish - Scallops, Cold Smoked']

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [119]:
d = {k:v if isinstance(v, list) else [v] for k, v in dict_cust_recom.items()}
df = pd.DataFrame.from_dict(d, orient='index').sort_index()
df.columns = 'Prod1  Prod2  Prod3 Prod4 Prod5 '.split()

display (df.head(20))

,Prod1,Prod2,Prod3,Prod4,Prod5
33,Butter - Unsalted,Wine - Ej Gallo Sierra Valley,Soup - Campbells Bean Medley,Wine - Blue Nun Qualitatswein,Chicken - Soup Base
200,Soup - Campbells Bean Medley,Muffin - Carrot Individual Wrap,Bay Leaf,Pork - Kidney,Wanton Wrap
264,Soupfoamcont12oz 112con,Wine - Two Oceans Cabernet,Bread - Italian Roll With Herbs,"Veal - Inside, Choice","Fish - Scallops, Cold Smoked"
356,"Veal - Inside, Choice",Lamb - Ground,Pomello,Butter - Unsalted,"Tart Shells - Sweet, 4"
412,Olive - Spread Tapenade,Sprouts - Baby Pea Tendrils,Wine - Blue Nun Qualitatswein,"Pepper - Black, Whole",Soup - Campbells Bean Medley
464,Butter - Unsalted,"Sauce - Gravy, Au Jus, Mix","Pepper - Black, Whole","Peas - Pigeon, Dry",Bar - Granola Trail Mix Fruit Nut
477,Olive - Spread Tapenade,Sprouts - Baby Pea Tendrils,Wine - Blue Nun Qualitatswein,"Veal - Inside, Choice","Pepper - Black, Whole"
639,Cod - Black Whole Fillet,Wine - Ej Gallo Sierra Valley,Yoghurt Tubes,"Pepper - Black, Whole",Soupfoamcont12oz 112con
649,Bar - Granola Trail Mix Fruit Nut,Wine - Magnotta - Belpaese,Appetizer - Mushroom Tart,"Peas - Pigeon, Dry","Pepper - Black, Whole"
669,"Veal - Inside, Choice",Sardines,Wine - Ej Gallo Sierra Valley,"Pepper - Black, Whole",Wine - Blue Nun Qualitatswein
694,Bar - Granola Trail Mix Fruit Nut,Potatoes - Idaho 100 Count,"Beets - Candy Cane, Organic",Knife Plastic - White,Sardines
756,"Veal - Inside, Choice",Grouper - Fresh,"Salsify, Organic",Butter - Unsalted,"Peas - Pigeon, Dry"
883,Knife Plastic - White,Sardines,Soup Campbells - Italian Wedding,Beef Wellington,"Salsify, Organic"
891,Cod - Black Whole Fillet,Soup - Campbells Bean Medley,Sherry - Dry,"Pepper - Black, Whole",Sprouts - Baby Pea Tendrils
1008,"Mushrooms - Black, Dried",Lamb - Ground,Soupfoamcont12oz 112con,"Pepper - Black, Whole",Soup - Campbells Bean Medley
1034,Beef - Top Sirloin - Aaa,Wine - Chardonnay South,Eggplant - Asian,"Sole - Dover, Whole, Fresh",Veal - Sweetbread
1066,Butter - Unsalted,Wine - Blue Nun Qualitatswein,Yoghurt Tubes,Knife Plastic - White,Soup - Campbells Bean Medley
1072,"Nut - Chestnuts, Whole",Skirt - 29 Foot,"Pork - Bacon, Double Smoked",Butter - Unsalted,Bar - Granola Trail Mix Fruit Nut
1336,Soup - Campbells Bean Medley,Butter - Unsalted,Bar - Granola Trail Mix Fruit Nut,"Pepper - Black, Whole",Wine - Crozes Hermitage E.
1428,Ketchup - Tomato,Cake - Cake Sheet Macaroon,Cheese - Cambozola,Anchovy Paste - 56 G Tube,"Peas - Pigeon, Dry"

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

In [120]:
similarity_m2 = pd.DataFrame(1/(1 + squareform(pdist(data_pivot.T, 'cosine'))), 
                         index=data_pivot.columns, columns=data_pivot.columns)
display(similarity_m2.head())

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.530003,0.563492,0.543546,0.542393,0.541054,0.522016,0.530783,0.533096,0.535293,...,0.530306,0.517987,0.527662,0.511471,0.534181,0.513809,0.528795,0.520208,0.529481,0.527142
200,0.530003,1.000000,0.537166,0.535098,0.521226,0.519193,0.556945,0.516729,0.536350,0.541451,...,0.545224,0.533067,0.555246,0.543554,0.530308,0.521925,0.573177,0.537284,0.526167,0.527280
264,0.563492,0.537166,1.000000,0.531963,0.550168,0.525368,0.538967,0.514932,0.537046,0.524193,...,0.546880,0.525550,0.535062,0.531806,0.553085,0.560225,0.548538,0.538340,0.554929,0.527142
356,0.543546,0.535098,0.531963,1.000000,0.525982,0.523986,0.536792,0.540890,0.516901,0.519482,...,0.536321,0.520565,0.533119,0.534066,0.528874,0.530406,0.520138,0.536202,0.544727,0.535974
412,0.542393,0.521226,0.550168,0.525982,1.000000,0.534073,0.542308,0.547743,0.530459,0.543050,...,0.527903,0.565369,0.528847,0.529278,0.541674,0.536686,0.519628,0.538710,0.546943,0.552636

In [121]:
dict_cust_recom2 = {}
unique_customers = list(data.CustomerID.unique())
print(len(unique_customers))


for x in unique_customers:
    similar_ids=list((similarity_m2[x].sort_values(ascending=False)[1:6]).index)
    records=data2.loc[data2['CustomerID'].isin(similar_ids)]
    top_products = (records.groupby(["ProductName"])["Quantity"].sum().reset_index()).sort_values("Quantity",ascending=False)
    records_bought=data2.loc[data2['CustomerID']==x]
    products_bought=list(records_bought.ProductName.unique())
    products_similar=list(top_products.ProductName.unique())
    products_to_recommend=[i for i in products_similar if i not in products_bought]
    top5=top_products.loc[top_products['ProductName'].isin(products_to_recommend)][:5]
    dict_cust_recom2[x] = list(top5['ProductName'])

1000

In [122]:
dict_cust_recom[264]

['Soupfoamcont12oz 112con',
 'Wine - Two Oceans Cabernet',
 'Bread - Italian Roll With Herbs',
 'Veal - Inside, Choice',
 'Fish - Scallops, Cold Smoked']